---
image: bodsch/molecule-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

prepare:
  stage: build

  script:
    - pip install --quiet --requirement test-requirements.txt

  after_script:
    - python --version
    - docker --version
    - ansible --version

test-job-default:
  stage: test
  script:
    - echo "Test default"
    - pip install --quiet --requirement test-requirements.txt
    - tox -e py38-ansible210 -- molecule test --scenario-name default
  artifacts:
    expire_in: 1 day

