---
# image: python:3.8
image: bodsch/molecule-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

#services:
#  - name: bodsch/molecule-dind

before_script:
  - python --version
  - docker version

stages:
  # - prepare  
  - test

.pre:
  stage: prepare

#  before_script:
#    - /usr/bin/python --version
#    - docker --version
#    - docker info

  script:
    - /usr/bin/python -m pip install --upgrade pip
    - pip install -r test-requirements.txt
    - tox --listenvs
    - /usr/bin/python --version
    - ansible --version

test-job-default:
  stage: test
  script:
    - echo "Test default"
    - tox -e py38-ansible210 -- molecule test --scenario-name default

