---

- name: create go-carbon.conf
  template:
    src: etc/go-carbon/go-carbon.conf.j2
    dest: /etc/go-carbon/go-carbon.conf
    backup: true
  notify:
    - restart go-carbon

- name: create storage-schemas.conf
  template:
    src: etc/go-carbon/storage-schemas.conf.j2
    dest: /etc/go-carbon/storage-schemas.conf
    backup: true
  notify:
    - restart go-carbon

- name: create storage-aggregation.conf
  template:
    src: etc/go-carbon/storage-aggregation.conf.j2
    dest: /etc/go-carbon/storage-aggregation.conf
    backup: true
  notify:
    - restart go-carbon
