---

- include: prepare.yml
  become: true
  tags:
    - go-carbon_prepare
    - go-carbon_configure #needed to load default vars (see merge ... between defaults and custom)

- include: download.yml
  become: true
  tags:
    - go-carbon_install

- include: install.yml
  become: true
  tags:
    - go-carbon_install

- include: configure.yml
  become: true
  tags:
    - go-carbon_configure

- include: service.yml
  become: true
  tags:
    - go-carbon_service
