---

- include: prepare.yml
  become: true
  tags:
    - preparations
    - configure #needed to load default vars (see merge ... between defaults and custom) 

- include: download.yml
  become: true
  tags:
    - installation

- include: installation.yml
  become: true
  tags:
    - installation

- include: configure.yml
  become: true
  tags:
    - configure

- include: service.yml
  become: true
  tags:
    - service
