---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''
  roles:
    - role: ansible-go-carbon
      vars:
        go_carbon_storage_schema:
          test:
            pattern: '^test\.'
            retentions: '5m:30d'
